import { defineConfig } from 'vite';

export default defineConfig({
    server: { port: 5173 },
    build: { assetsInlineLimit: 0 },
    optimizeDeps: {
        noDiscovery: true,
        include: [
            'earcut',
            '@babylonjs/core/Engines/engine',
            '@babylonjs/core/scene',
            '@babylonjs/core/Meshes/meshBuilder',
            '@babylonjs/core/Meshes/mesh',
            '@babylonjs/core/Meshes/transformNode',
            '@babylonjs/core/Meshes/polygonMesh',
            '@babylonjs/core/Maths/math.vector',
            '@babylonjs/core/Maths/math.color',
            '@babylonjs/core/Materials/standardMaterial',
            '@babylonjs/core/Materials/PBR/pbrMaterial',
            '@babylonjs/core/Materials/Textures/dynamicTexture',
            '@babylonjs/core/Materials/Textures/texture',
            '@babylonjs/core/Materials/Textures/baseTexture',
            '@babylonjs/core/Lights/hemisphericLight',
            '@babylonjs/core/Lights/directionalLight',
            '@babylonjs/core/Lights/pointLight',
            '@babylonjs/core/Lights/Shadows/shadowGenerator',
            '@babylonjs/core/Lights/Shadows/shadowGeneratorSceneComponent',
            '@babylonjs/core/Cameras/arcRotateCamera',
            '@babylonjs/core/Loading/sceneLoader',
            '@babylonjs/core/assetContainer',
            '@babylonjs/core/Animations/animationGroup',
            '@babylonjs/core/Events/keyboardEvents',
            '@babylonjs/core/Events/pointerEvents',
            '@babylonjs/core/Layers/glowLayer',
            '@babylonjs/core/Particles/particleSystem',
            '@babylonjs/core/Particles/particleSystemComponent',
            '@babylonjs/loaders/glTF',
        ],
    },
});
