/**
 * PromptCard.ts — 8 Prompt Card definitions for A2.
 * These are spell/event cards played from hand alongside character cards.
 */
import type { PromptCardDef } from './types';

export const PROMPT_DEFS: PromptCardDef[] = [
    {
        id: 'prompt_alaz_surge',
        name: 'Alaz Dalgası',
        description: 'Tüm ateş birimlerine 2 tur boyunca +4 saldırı gücü ver.',
        manaCost: 3,
        effectType: 'berserker_rage',
        magnitude: 4,
        duration: 2,
        targetTeam: 'self',
        faction: 'fire',
    },
    {
        id: 'prompt_frost_nova',
        name: 'Buz Noktası',
        description: 'Bir bölgedeki tüm düşman birimleri 1.5 saniye dondur.',
        manaCost: 4,
        effectType: 'freeze_area',
        magnitude: 1.5,
        duration: 0,
        targetTeam: 'enemy',
        faction: 'ice',
    },
    {
        id: 'prompt_spirit_call',
        name: 'Ruh Çağrısı',
        description: 'Rastgele bir lanede 1 geçici ruh birimi çağır (2 tur).',
        manaCost: 3,
        effectType: 'summon_spirit',
        magnitude: 1,
        duration: 2,
        targetTeam: 'self',
        faction: 'neutral',
    },
    {
        id: 'prompt_mana_flow',
        name: 'Mana Akışı',
        description: 'Bir sonraki turda +3 bonus mana kazan.',
        manaCost: 2,
        effectType: 'mana_surge',
        magnitude: 3,
        duration: 1,
        targetTeam: 'self',
        faction: 'neutral',
    },
    {
        id: 'prompt_earthfire',
        name: 'Toprak Ateşi',
        description: 'Orta lanedeki tüm düşmanlara 25 hasar ver.',
        manaCost: 4,
        effectType: 'damage_aoe',
        magnitude: 25,
        duration: 0,
        targetTeam: 'enemy',
        faction: 'fire',
    },
    {
        id: 'prompt_umay_blessing',
        name: 'Umay\'ın Nimeti',
        description: 'Ateş birimlerini %30 HP iyileştir.',
        manaCost: 3,
        effectType: 'heal_ally',
        magnitude: 0.30,
        duration: 0,
        targetTeam: 'self',
        faction: 'neutral',
    },
    {
        id: 'prompt_ice_shield',
        name: 'Buz Kalkanı',
        description: 'Tüm ateş birimlerine 2 tur boyunca kalkan ver (30 hasar emer).',
        manaCost: 3,
        effectType: 'shield_all',
        magnitude: 30,
        duration: 2,
        targetTeam: 'self',
        faction: 'ice',
    },
    {
        id: 'prompt_wind_step',
        name: 'Rüzgar Adımı',
        description: 'Ateş birimleri 2 tur boyunca %60 daha hızlı hareket eder.',
        manaCost: 2,
        effectType: 'speed_boost',
        magnitude: 0.60,
        duration: 2,
        targetTeam: 'self',
        faction: 'neutral',
    },
];
